"""add body field to custom_api

Revision ID: b2c517a02b3b
Revises: dd20b4878cf1
Create Date: 2026-05-06 15:36:01.510171

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c517a02b3b"
down_revision: Union[str, None] = "dd20b4878cf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("custom_apis", sa.Column("body", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_apis", "body")
    # ### end Alembic commands ###
