"""add_agent_type_to_tasks_table

Revision ID: be6f77416f06
Revises: 222f2073c886
Create Date: 2025-12-08 13:43:28.882478

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be6f77416f06"
down_revision: Union[str, None] = "222f2073c886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if mcp_servers_legacy table exists before dropping it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if inspector.has_table("mcp_servers_legacy"):
        if inspector.has_index("mcp_servers_legacy", "ix_mcp_servers_id"):
            op.drop_index(op.f("ix_mcp_servers_id"), table_name="mcp_servers_legacy")
        op.drop_table("mcp_servers_legacy")

    # Check if mcp_servers table exists before creating index
    if inspector.has_table("mcp_servers"):
        if not inspector.has_index("mcp_servers", "ix_mcp_servers_id"):
            op.create_index(
                op.f("ix_mcp_servers_id"), "mcp_servers", ["id"], unique=False
            )

    # Check if columns already exist before adding them
    if inspector.has_table("tasks"):
        existing_columns = [col["name"] for col in inspector.get_columns("tasks")]
        if "agent_type" not in existing_columns:
            op.add_column(
                "tasks", sa.Column("agent_type", sa.String(length=20), nullable=True)
            )

        if "agent_config" not in existing_columns:
            op.add_column("tasks", sa.Column("agent_config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    from alembic import context
    from sqlalchemy.engine.reflection import Inspector

    bind = context.get_bind()
    inspector = Inspector.from_engine(bind)

    # Check if columns exist before dropping
    tables = inspector.get_table_names()
    if "tasks" in tables:
        existing_columns = [col["name"] for col in inspector.get_columns("tasks")]
        if "agent_config" in existing_columns:
            dialect_name = bind.dialect.name
            if dialect_name == "sqlite":
                with op.batch_alter_table("tasks", recreate="auto") as batch_op:
                    if "agent_config" in existing_columns:
                        batch_op.drop_column("agent_config")
                    if "agent_type" in existing_columns:
                        batch_op.drop_column("agent_type")
            else:
                if "agent_config" in existing_columns:
                    op.drop_column("tasks", "agent_config")
                if "agent_type" in existing_columns:
                    op.drop_column("tasks", "agent_type")

    # Try to drop index if it exists
    if "mcp_servers" in tables:
        existing_indexes = [idx["name"] for idx in inspector.get_indexes("mcp_servers")]
        if "ix_mcp_servers_id" in existing_indexes:
            try:
                op.drop_index(op.f("ix_mcp_servers_id"), table_name="mcp_servers")
            except Exception:
                pass  # Index might not exist
    op.create_table(
        "mcp_servers_legacy",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "transport", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_default", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("mcp_servers_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("mcp_servers_pkey")),
    )
    op.create_index(
        op.f("ix_mcp_servers_id"), "mcp_servers_legacy", ["id"], unique=False
    )
    # ### end Alembic commands ###
