"""Agent service facade and shared tracing utilities."""

from .exceptions import (
    AgentConfigurationError,
    AgentException,
    AgentToolError,
    ContextCompactionError,
    ContextError,
    DAGDeadlockError,
    DAGDependencyError,
    DAGError,
    DAGPlanGenerationError,
    DAGStepError,
    LLMError,
    LLMNotAvailableError,
    LLMResponseError,
    MaxIterationsError,
    PatternError,
    PatternExecutionError,
    ReActError,
    ReActParsingError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    create_execution_error,
)
from .service import AgentService

__all__ = [
    "AgentService",
    "AgentException",
    "AgentConfigurationError",
    "LLMError",
    "LLMNotAvailableError",
    "LLMResponseError",
    "ToolError",
    "ToolNotFoundError",
    "ToolExecutionError",
    "PatternError",
    "PatternExecutionError",
    "MaxIterationsError",
    "DAGError",
    "DAGPlanGenerationError",
    "DAGStepError",
    "DAGDependencyError",
    "DAGDeadlockError",
    "ReActError",
    "ReActParsingError",
    "ContextError",
    "ContextCompactionError",
    "AgentToolError",
    "create_execution_error",
]
