"""Token usage tracking using contextvars.

This module provides a thread-safe way to track token usage across LLM calls
without modifying function signatures. Using contextvars allows the token
statistics to be automatically collected during task execution.
"""

import contextvars
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class TokenUsage:
    """Token usage statistics for a task or operation.

    Attributes:
        input_tokens: Number of tokens in prompts sent to LLM
        output_tokens: Number of tokens generated by LLM
        llm_calls: Number of LLM API calls made
        details: Detailed breakdown by model/call type
    """

    input_tokens: int = 0
    output_tokens: int = 0
    llm_calls: int = 0
    tool_calls: int = 0
    details: List[Dict] = field(default_factory=list)

    @property
    def total_tokens(self) -> int:
        """Total tokens used (input + output)."""
        return self.input_tokens + self.output_tokens

    def add_input_tokens(
        self,
        tokens: int,
        model: str = "",
        call_type: str = "",
        model_id: str = "",
        cached_tokens: int = 0,
        cache_write_tokens: int = 0,
    ) -> None:
        """Add input tokens from a prompt.

        ``cached_tokens`` is the subset of ``tokens`` served from the provider's
        prompt cache (usually billed cheaper); 0 when unknown/unsupported.
        ``cache_write_tokens`` is the subset of ``tokens`` written to the cache
        this call (Claude bills these at a premium); 0 when unknown.
        """
        self.input_tokens += tokens
        if model or call_type:
            self.details.append(
                {
                    "type": "input",
                    "tokens": tokens,
                    "cached_tokens": cached_tokens,
                    "cache_write_tokens": cache_write_tokens,
                    "model": model,
                    "model_id": model_id,
                    "call_type": call_type,
                }
            )

    def add_output_tokens(
        self, tokens: int, model: str = "", call_type: str = "", model_id: str = ""
    ) -> None:
        """Add output tokens from a completion."""
        self.output_tokens += tokens
        if model or call_type:
            self.details.append(
                {
                    "type": "output",
                    "tokens": tokens,
                    "model": model,
                    "model_id": model_id,
                    "call_type": call_type,
                }
            )

    def increment_llm_calls(self) -> None:
        """Increment the LLM call counter."""
        self.llm_calls += 1

    def increment_tool_calls(self, count: int = 1) -> None:
        """Increment the tool-call counter (one per tool invocation)."""
        self.tool_calls += count

    def merge(self, other: "TokenUsage") -> None:
        """Merge another TokenUsage into this one."""
        self.input_tokens += other.input_tokens
        self.output_tokens += other.output_tokens
        self.llm_calls += other.llm_calls
        self.tool_calls += other.tool_calls
        self.details.extend(other.details)

    def to_dict(self) -> Dict:
        """Convert to dictionary for serialization."""
        return {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "total_tokens": self.total_tokens,
            "llm_calls": self.llm_calls,
            "tool_calls": self.tool_calls,
            "details": self.details,
        }

    @classmethod
    def from_dict(cls, data: Dict) -> "TokenUsage":
        """Create from dictionary."""
        return cls(
            input_tokens=data.get("input_tokens", 0),
            output_tokens=data.get("output_tokens", 0),
            llm_calls=data.get("llm_calls", 0),
            tool_calls=data.get("tool_calls", 0),
            details=data.get("details", []),
        )


# ContextVar for thread-local token tracking. Default is None (not a shared
# TokenUsage instance): a single shared default would accumulate forever for
# untracked paths (preview/builder that never call set_token_usage), leaking
# memory. get_token_usage() lazily creates a per-context instance instead.
token_context: contextvars.ContextVar[Optional[TokenUsage]] = contextvars.ContextVar(
    "token_context", default=None
)


class TokenContextManager:
    """Manager for token context with automatic cleanup.

    Example:
        with TokenContextManager() as manager:
            # LLM calls here will be tracked
            await llm.chat(messages)
        # After exiting, usage can be retrieved
        usage = manager.get_usage()
    """

    def __init__(self, parent_usage: Optional[TokenUsage] = None):
        """Initialize the context manager.

        Args:
            parent_usage: Optional parent TokenUsage to merge into
        """
        self._token_usage = TokenUsage()
        if parent_usage:
            self._token_usage.merge(parent_usage)
        self._previous_token: Optional[TokenUsage] = None

    def __enter__(self) -> "TokenContextManager":
        """Enter the context and start tracking."""
        self._previous_token = token_context.get(None)
        token_context.set(self._token_usage)
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Exit the context and restore the previous state.

        Restores whatever was there before (``None`` when nothing was set), so
        leaving a manager block doesn't reintroduce a lingering shared
        TokenUsage instance — matching the None default on the ContextVar.
        """
        token_context.set(self._previous_token)

    def get_usage(self) -> TokenUsage:
        """Get the current token usage."""
        return self._token_usage

    def add_input_tokens(
        self, tokens: int, model: str = "", call_type: str = ""
    ) -> None:
        """Add input tokens (convenience method)."""
        self._token_usage.add_input_tokens(tokens, model, call_type)

    def add_output_tokens(
        self, tokens: int, model: str = "", call_type: str = ""
    ) -> None:
        """Add output tokens (convenience method)."""
        self._token_usage.add_output_tokens(tokens, model, call_type)


# Global functions for easier access


def get_token_usage() -> TokenUsage:
    """Get the current token usage, lazily creating a per-context instance."""
    usage = token_context.get()
    if usage is None:
        usage = TokenUsage()
        token_context.set(usage)
    return usage


def _coerce_int(value: Any) -> int:
    """Best-effort int; 0 if the value isn't a usable number (e.g. None/mock)."""
    if isinstance(value, bool):
        return int(value)
    try:
        return int(value)
    except (TypeError, ValueError):
        # None/absent is expected (provider omitted the field) — stay quiet.
        # A present-but-malformed value signals a provider-adapter bug worth
        # surfacing rather than silently billing it as zero.
        if value is not None:
            logger.warning("Discarding non-numeric token count: %r", value)
        return 0


def _usage_field(usage: Any, name: str) -> Any:
    """Read a field from a provider usage payload (SDK object or plain dict)."""
    if isinstance(usage, dict):
        return usage.get(name)
    return getattr(usage, name, None)


def extract_cached_input_tokens(usage: Any) -> int:
    """Prompt-cache-hit input tokens from an OpenAI-style usage payload.

    Handles both attribute-style SDK objects and plain dicts (streaming chunks
    often arrive as dicts). DeepSeek reports ``prompt_cache_hit_tokens``;
    OpenAI/DashScope/Zhipu report ``prompt_tokens_details.cached_tokens``.
    Returns 0 when unavailable.
    """
    if usage is None:
        return 0
    hit = _usage_field(usage, "prompt_cache_hit_tokens")
    if hit is not None:
        value = max(0, _coerce_int(hit))
        if value:
            return value
        # Some proxies emit prompt_cache_hit_tokens=0 as a default while the
        # real count sits in prompt_tokens_details; fall through to it.
    details = _usage_field(usage, "prompt_tokens_details")
    if details is not None:
        return max(0, _coerce_int(_usage_field(details, "cached_tokens")))
    return 0


def aggregate_token_usage_by_model(details: Any) -> List[Dict[str, Any]]:
    """Aggregate persisted token detail entries by the actual model used.

    ``model_id`` is preferred as the identity because different configured
    models can share a provider-facing name. A legacy name-only group is
    merged into an id-backed group only when that name identifies exactly one
    configured model. Entries without either an id or name are retained as an
    unattributed group rather than silently dropping tokens from the breakdown.
    """
    if not isinstance(details, list):
        return []

    grouped: Dict[tuple[str, str], Dict[str, Any]] = {}
    for detail in details:
        if not isinstance(detail, dict):
            continue
        token_type = detail.get("type")
        if token_type not in {"input", "output"}:
            continue
        tokens = max(0, _coerce_int(detail.get("tokens")))
        if tokens == 0:
            continue

        raw_model_id = detail.get("model_id")
        raw_model_name = detail.get("model")
        model_id = raw_model_id.strip() if isinstance(raw_model_id, str) else ""
        model_name = raw_model_name.strip() if isinstance(raw_model_name, str) else ""
        key = ("id", model_id) if model_id else ("name", model_name)
        if not model_id and not model_name:
            key = ("unknown", "")

        aggregate = grouped.setdefault(
            key,
            {
                "model_id": model_id,
                "model_name": model_name,
                "input_tokens": 0,
                "output_tokens": 0,
                "total_tokens": 0,
                "cached_input_tokens": 0,
                "cache_write_input_tokens": 0,
            },
        )
        # Some legacy adapters only stamped the name on one of the pair.
        if not aggregate["model_name"] and model_name:
            aggregate["model_name"] = model_name
        aggregate[f"{token_type}_tokens"] += tokens
        aggregate["total_tokens"] += tokens
        if token_type == "input":
            # Legacy entries predate cache tracking; clamp to the entry's
            # own input tokens so malformed data can't exceed the total.
            cached = min(tokens, max(0, _coerce_int(detail.get("cached_tokens"))))
            cache_write = min(
                tokens, max(0, _coerce_int(detail.get("cache_write_tokens")))
            )
            aggregate["cached_input_tokens"] += cached
            aggregate["cache_write_input_tokens"] += cache_write

    id_keys_by_name: Dict[str, List[tuple[str, str]]] = {}
    for key, aggregate in grouped.items():
        if key[0] == "id" and aggregate["model_name"]:
            id_keys_by_name.setdefault(aggregate["model_name"], []).append(key)

    for key, aggregate in list(grouped.items()):
        if key[0] != "name":
            continue
        matching_id_keys = id_keys_by_name.get(aggregate["model_name"], [])
        if len(matching_id_keys) != 1:
            continue
        target = grouped[matching_id_keys[0]]
        target["input_tokens"] += aggregate["input_tokens"]
        target["output_tokens"] += aggregate["output_tokens"]
        target["total_tokens"] += aggregate["total_tokens"]
        target["cached_input_tokens"] += aggregate["cached_input_tokens"]
        target["cache_write_input_tokens"] += aggregate["cache_write_input_tokens"]
        del grouped[key]

    sorted_groups = sorted(
        grouped.values(),
        key=lambda item: (
            -item["total_tokens"],
            item["model_name"].casefold(),
            item["model_id"].casefold(),
        ),
    )
    return [
        {
            "model_id": item["model_id"],
            "model_name": item["model_name"],
            "input_tokens": item["input_tokens"],
            "output_tokens": item["output_tokens"],
            "cached_input_tokens": item["cached_input_tokens"],
            "cache_write_input_tokens": item["cache_write_input_tokens"],
        }
        for item in sorted_groups
    ]


def add_token_usage(
    input_tokens: int = 0,
    output_tokens: int = 0,
    model: str = "",
    call_type: str = "",
    model_id: str = "",
    cached_input_tokens: int = 0,
    cache_write_input_tokens: int = 0,
) -> None:
    """Add token usage to the current context.

    Args:
        input_tokens: Number of input tokens
        output_tokens: Number of output tokens
        model: Model name for tracking
        call_type: Type of call (chat, stream_chat, vision_chat, etc.)
        model_id: Unique model id (disambiguates identically-named models)
        cached_input_tokens: Subset of input_tokens served from prompt cache
        cache_write_input_tokens: Subset of input_tokens written to the cache
    """
    # Coerce defensively: a provider/response that yields a non-int token count
    # (or a mock in tests) must never crash the LLM call over accounting.
    input_tokens = _coerce_int(input_tokens)
    output_tokens = _coerce_int(output_tokens)
    cached_input_tokens = _coerce_int(cached_input_tokens)
    cache_write_input_tokens = _coerce_int(cache_write_input_tokens)

    usage = get_token_usage()
    if input_tokens or output_tokens:
        # Increment LLM call counter for each API call
        usage.increment_llm_calls()
    if input_tokens:
        usage.add_input_tokens(
            input_tokens,
            model,
            call_type,
            model_id,
            cached_input_tokens,
            cache_write_input_tokens,
        )
    if output_tokens:
        usage.add_output_tokens(output_tokens, model, call_type, model_id)

    logger.debug(
        f"Token usage added: input={input_tokens}, output={output_tokens}, "
        f"model={model}, model_id={model_id}, call_type={call_type}, "
        f"total_input={usage.input_tokens}, total_output={usage.output_tokens}, "
        f"total_calls={usage.llm_calls}"
    )


def add_tool_call_usage(count: int = 1) -> None:
    """Record one (or more) tool invocations on the current context."""
    get_token_usage().increment_tool_calls(count)


def reset_token_usage() -> TokenUsage:
    """Reset and return the current token usage."""
    new_usage = TokenUsage()
    token_context.set(new_usage)
    return new_usage


def set_token_usage(usage: TokenUsage) -> TokenUsage:
    token_context.set(usage)
    return usage


def get_and_reset_token_usage() -> TokenUsage:
    """Get current usage and reset the context."""
    usage = get_token_usage()
    reset_token_usage()
    return usage
